# ENVIRONMENT
environment: :development

# GENERAL IRC SETTINGS
nick: 'XeniaTest'
realname: 'PUGBOT testing'
user: 'XeniaTest'
server: 'irc.quakenet.org'
channels:
  - '#xzanth'
messages_per_second: 0.45
server_queue_size: 5

# IDENTIFY SETTINGS
username: 'xzbot'
password: <%= ENV["TESTING_AUTH_PASSWORD"] %>
auth: :secure_quakenet

# PUGBOT SETTINGS
pug_channel: '#xzanth'
link: '<http://webchat.quakenet.org/?channels=xzanth|#xzanth>'
integrate: true
default_file: 'default_test_list'

# INTEGRATE SETTINGS
slack_key: <%= ENV["TESTING_SLACK_KEY"] %>
integrations:
  - :slack

# AUTH-AUTOVOICE SETTINGS
wait_until_opped: true
check_periodically: true

# COMMANDS SETTINGS
help_response: :notice

# DATABASE SETTINGS
db_type: "sqlite"
db_file: "database.sqlite"

# LOGGING
log_file: "logfile.log"

# WEB SERVER
web_port: 9494
